### PR TITLE
Replaced raw image data with url in project list. Fixes #1780

### LINKED ISSUE #1780: getting project list should not include project thumbnails
Project thumbnails should be lazily loaded rather than eagerly loaded with all the projects on viewing cloud projects.

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

**Comment by brollb** [comment]
@hamidzr: can you check this out with the project lists used on netsblox.org? It may not actually require any changes to the client code if you are just using the `Thumbnail` contents directly in the image tags...

**Comment by hamidzr** [comment]
with a small change, it works. we have to change the path from relative to absolute on the frontend

**Comment by hamidzr** [comment]
but it actually might be better to change it so that the thumbnail is an absolute path and then it requires no change anywhere that thumbnail might have been used (mobile app, frontend, etc)

**Comment by brollb** [comment]
Awesome. How about we go ahead with those changes for netsblox.org and I will merge this!

**Comment by hamidzr** [comment]
Updateling the pr to an absolute path wouldn't be better ?

**Pull request merged**
