### PR TITLE
Removed the sorting of numbers. Fixes #1882

### LINKED ISSUE #1882: Charting service should not sort points before plotting
Currently, the charting service sorts the provided points. This should not be the case as it should plot the points in whatever order is provided.

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

**Comment by hamidzr** [comment]
are the older chart calls being used? right now we have backward compatibility for those but this could break some of them and if they are being used we could add it only to `chart.drawBarChart`

**Comment by brollb** [comment]
yeah, I still have to update those

**Comment by hamidzr** [comment]
This is breaking the client chart tests. (at least the timeseries one)

**Comment by brollb** [comment]
Yeah, it's still a work in progress :)

2018. febr. 27. 15:29 ezt írta ("Hamid Zare" <notifications@github.com>):

**Comment by brollb** [comment]
I added the updated chart tests and it should be good to go now (afaik).

**Comment by hamidzr** [comment]
It's worth noting that this removes the sorting for timeseries data

**Comment by hamidzr** [comment]
Thanks

**Pull request merged**
