### PR TITLE
auto generated help messages for services Fixes #1696

### LINKED ISSUE #1696: service blocks should auto generate documentation for user
we need to generate help documents for the user from the parsed metadata #1362: variable types, defaults, whether they are optional, descriptions, and expected values.

### PR DESCRIPTION
**Pull request by hamidzr**
displays help dialog boxes for services block based on the selected service + method from JSDoc blocks

### CODE REVIEW

**Comment by hamidzr** [comment]
we just need a better wording for a general description of the services block

**Comment by brollb** [comment]
We need to add bullet points for the inputs and adjust the formatting. Maybe we should bold the input argument names to make them more obvious

**Comment by hamidzr** [comment]
This gets the basic help functionality in there and add decorations in
another PR

**Comment by brollb** [comment]
Good point. I will merge this and we can do the touch ups in another PR

**Pull request merged**
