### PR TITLE
more place information for gelolocate fixes #980

### LINKED ISSUE #980: geolocate nearby search should return more details
-lat
-lon
-name
-type

### PR DESCRIPTION
**Pull request by hamidzr**

### CODE REVIEW

**Comment by brollb** [comment]
can you fix the code climate issue?

**Comment by brollb** [comment]
Could you update this to use the updated structured data helpers?

**Comment by brollb** [comment]
Can you update it so it returns `[]` if nothing found? Currently, the example errors if nothing is found

**Comment by hamidzr** [comment]
Done, it will return [] if it finds no results but will show an error if sth is wrong with the api call

**Pull request merged**
