### PR TITLE
reorganize services

### PR DESCRIPTION
**Pull request by dragazo**
@brollb Adds all the service category reorganization we talked about. _Note: requires matching [browser PR](https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/1336)._

This changes the service jsdoc parser to inject a `['global']` category if no categories are specified (so we don't have to have a special case for no categories). The browser PR and doc gen have been updated accordingly.

Also renames AlphaVantage to FinancialData like Akos mentioned - should be non-breaking since this was an alpha service.

### CODE REVIEW

**Comment by brollb** [comment]
Nice! It would've been a bit easier to review if this had been split into 2 PRs: one for global + categories and one for reorganizing the services.

On the topic of global + categories, I am not a fan of propagating the "global" keyword through to all the clients. Why not just add an empty list of categories to the list of categories for the service? Each list of categories is really just a list of valid paths to the service; if one of the valid paths is empty, then the service should be available at the top-level, too. This would also require a smaller change to the client and would avoid special-casing `global` outside the server (which would be ideal).

**Comment by dragazo** [comment]
Sure, changing it to empty list should work - it would need a special case in the parser unless we want to make `@category\n` (no category sequence) legal. Either way, I can change that quickly when I get out of classes - changing between `@category\n` and `@category global` would be easy and server-side only.

On a separate note, I noticed when updating doc gen that we've already had breaking changes exposed to clients, they just didn't break in this case because of client-side javascript conversions. For instance the doc generator uses category as a dict key (since they used to be strings) but now they're a list of strings and the only reason it didn't crash is cause javascript converts dict keys to string/number implicitly and categories so far have not used commas (but could since they're semicolon separated iirc)

**Comment by brollb** [comment]
> unless we want to make @category\n (no category sequence) legal

I would hard error and just crash the server if this happens :)

> (since they used to be strings) 

When did they change? I didn't think there had been any recent changes to the format used for the representation of categories.

**Comment by dragazo** [comment]
Ok, just changed to using `@category GLOBAL` and it'll catch other casings as hard errors.

Oh actually, looking at git blame it looks like you're right and it hasn't changed recently. Maybe I just assumed it was a string and javascript gaslit me by working.

**Comment by brollb** [comment]
Thanks, @dragazo!

**Pull request merged**
