### PR TITLE
structured data helpers fixed #989

### PR DESCRIPTION
**Pull request by hamidzr**
to help access data from structured arrays

### CODE REVIEW

**Comment by brollb** [comment]
`value ___ in ___`

**Comment by hamidzr** [comment]
added setter and updated the description and name

**Comment by brollb** [comment]
- the set block reports `Bad list structure` sometimes but this is basically failing silently since the block doesn't return anything. It should probably throw an exception instead.
- checking the block structure in the set block should probably support an empty list (empty struct)
- there was also an issue in the LIBRARIES file

They were all pretty minor so I just took care of these issues

**Comment by hamidzr** [comment]
Thanks!

**Pull request merged**
