### PR TITLE
Improve WordGuess feedback method

### PR DESCRIPTION
**Pull request by brollb**
@gsteinLTU - I added the failing test for #3360. Could you take care of this?

### CODE REVIEW

**Comment by gsteinLTU** [comment]
Thanks for sending the test case in. It's passing it and a few extra cases I added for other scenarios now.

**Comment by gsteinLTU** [comment]
By the way, did this happen in the live service or only when `_calculateMatches` was run in a vacuum for the test? The issue seemed to be the test passing a string to it, instead of an array as was given to it in the service, since the string was immutable. Good catch either way though, the method definitely should have been taking both inputs as strings (which is both intuitive and what I annotated it with).

**Comment by brollb** [comment]
Yeah, Ákos ran into it with the same word (crack).

**Comment by gsteinLTU** [comment]
Interesting, let me try adding a test for the service version then before we finish this.

**Comment by gsteinLTU** [comment]
@brollb Seems to pass the additional tests, so it should be good.

**Comment by brollb** [comment]
Looks good! Thanks, @gsteinLTU!

**Pull request merged**
