### PR TITLE
support to open private projects in appMode

### PR DESCRIPTION
**Pull request by hamidzr**

### CODE REVIEW

**Comment by brollb** [comment]
Do you want to merge this into master or stable? It looks like it could be a decent candidate for stable rather than master.

However, if it is not that urgent or blocking, it might be better to merge it into master instead.

**Comment by hamidzr** [comment]
yea stable is a better target. updated the base

**Comment by brollb** [comment]
Do you want to make/fix this issue in the netsblox client code repo, too?

**Comment by hamidzr** [comment]
I'm adding it over there too https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/issues/403

**Pull request merged**
