### PR TITLE
764 google trends rpc

### PR DESCRIPTION
**Pull request by hamidzr**

### CODE REVIEW

**Comment by brollb** [comment]
Can you check out some of the code climate issues? Then I can take a look at it

**Comment by hamidzr** [comment]
done, there is only some todo tags left.

**Comment by brollb** [comment]
Can you resolve the TODO's? or is there a reason they should be merged into master as is?

**Comment by hamidzr** [comment]
cleaned up the examples and added new functionality, 
caching results to reduce external API calls. 
+ I'm not sure about the project name ( if it matches the directory name ). should I lose the hyphen in g-trends? make it googletrends? 
+ still using the demo for geonames API, assuming they have no solid quota on api calls.. ( since there is no secure authentication )

**Comment by brollb** [comment]
For the project name, I would probably use `google-trends`. For the username, I would do something like:
```
geoNamesUsername = process.env.GOOGLE_TRENDS_USERNAME || 'demo';
```

**Comment by brollb** [comment]
I would also check out the code climate issues

**Comment by hamidzr** [comment]
how do I mark changes as done?

**Comment by brollb** [comment]
Thanks, @hamidzr!

**Pull request merged**
