### PR TITLE
Input type docs

### LINKED ISSUE #3249: Generate RPC input type documentation
It would be great if we could generate documentation for RPC input types automatically and link to them where they are used in the RPC docs.

### PR DESCRIPTION
**Pull request by dragazo**
Closes #3249. We now generate a doc page for input types from the types metadata. All types in the docs are now generated using `displayName` (only difference so far is `Array -> List`). Fixed the issue where services with zero un-categorized rpcs would show an empty "RPCS" header. Updated existing type descriptions to be more useful with dynamic links to related services/rpcs - this is added as a new metadata field `rawDescription`, while `description` is a human-readable form (just like service metadata does).

RPC docs now link to their type entry. I wanted to do this by embedding links inside the inline code blocks, but sphinx doesn't allow that, so currently there's just a little `(ref)` link beside the type that takes you to the top level type (e.g., `T<U<V>>` currently just links to `T`, though the user can scroll down to find the others).

### CODE REVIEW

**Review by brollb — CHANGES_REQUESTED** [review]
Nice work! This will be nice to have :)

Here are a few comments:
- There might be a better name for the section rather than "Input Types". Although this makes sense in the source code, this isn't really obvious from the documentation since it could refer to anything. Maybe something like "RPC Argument Types" or "RPC Input Types" would be more clear.
- It might be nice to hide duplicate types with the same display name. Specifically, I am thinking about `SerializedFunction`. It doesn't actually need it's own section for users since it is really an alias for `Function` as far as users are concerned. (It matters for the RPC implementation, of course!)
- There might be a better option for the text "(ref)". Maybe something more verbose like "reference"? Or maybe there is a help icon we can use with meaningful title text? (I have used this in the past: https://useiconic.com/open)
- Some of the links to the services don't seem to be working. See below:
DeepinScreenshot_select-area_20210910125932
- It might be good to start thinking about how we could automatically record the service with the type definition. This actually shouldn't be too hard. I will take a pass at this and add a comment in a minute. Anyway, this would be nice so the types could be organized by the service and/or be recorded in an autogenerated section for the service.

**Comment by dragazo** [comment]
I switched out `(ref)` for `info` for the type links and changed the page title.

To keep things from being confusing, I actually wrote `defineType` to prevent two types from having the same display name. In the most recent commit, I've softened that constraint by adding a `hidden` flag - same display name is only a conflict if they're both non-hidden. I changed `SerializedFunction` to hidden with display name `Function`, so everything should link up properly and it'll only appear once.

For the broken links thing, I think those are broken on your end because you don't have those services (like PhoneIoT) set up on the machine you built the docs on, so sphinx couldn't resolve the target. I think that wouldn't be a problem on the main server, though, since it has everything set up.

**Comment by dragazo** [comment]
> Makes sense. I am a little worried about @alpha services since they may define custom types but won't be enabled on the production server :/

Yeah that would be an issue, but once we have the scoped types, we can just generate type docs for the services that are actually loaded.

**Review by brollb — APPROVED** [review]
LGTM. Nice work, @dragazo!

**Pull request merged**
