### PR TITLE
Creating service for ThingSpeak. Fix #1124

### LINKED ISSUE #1124: thingsspeak IOT api
https://thingspeak.com/channels/107204/feed.json
https://thingspeak.com/channels/public
https://www.mathworks.com/help/thingspeak/rest-api.html
- create / get charts: https://www.mathworks.com/help/thingspeak/create-a-chart.html

### PR DESCRIPTION
**Pull request by ellienguyen**

### CODE REVIEW

**Comment by ellienguyen** [comment]
The example depends on #1131 and #1283 to work properly
image
This is a screenshot of the example

**Comment by hamidzr** [comment]
@ellienguyen one of the tests are failing 
`  1 failing

  1) thingspeak-iot interfaces /thingspeakIoT interfaces publicChannel args should be tagString:
     Error: publicChannel is not supported by the RPC!
      at MockRPC.getArgumentsFor (test/assets/mock-rpc.js:39:11)
      at Context.<anonymous> (test/assets/utils.js:115:36)
` 
which is just a simple function rename. 

Also do you think we can have a private key option on the `channelFeed` method? then if it is set the service can use that when making a call so that users can access their private feeds. [source](https://www.mathworks.com/help/thingspeak/get-a-channel-feed.html)

**Comment by hamidzr** [comment]
there is a problem with distance, it's being set to 1000km despite the input.

**Comment by hamidzr** [comment]
should we close this PR as we have another one up to finish-up the work on this service?

**Comment by brollb** [comment]
Moving to https://github.com/NetsBlox/NetsBlox/pull/1347

**Pull request closed without merging**
