### PR TITLE
time filter for earthquakes rpc fixes #966

### LINKED ISSUE #966: Earthquakes should support time filtering

### PR DESCRIPTION
**Pull request by hamidzr**
filter earthquake events by start and end date passed as timestamp or js valid date string

### CODE REVIEW

**Comment by brollb** [comment]
Hmmmm... These tests should be breaking since you changed the interface for the earthquake example without updating the tests... maybe we are missing tests for the earthquakes api

**Comment by hamidzr** [comment]
good point. will take a look tomorrow.

**Comment by hamidzr** [comment]
yep the tests are missing.

**Comment by hamidzr** [comment]
also added magnitude filtering for earthquakes

**Comment by brollb** [comment]
thanks!

**Pull request merged**
