### PR TITLE
eclipse conditionHistoryRange Fixes #1437

### LINKED ISSUE #1437: eclipse service should have condition range method

### PR DESCRIPTION
**Pull request by hamidzr**

### CODE REVIEW

**Comment by brollb** [comment]
Can you add a test for this rpc?

**Comment by hamidzr** [comment]
this rpc same as temperatureRange falls back to stationsreadings method which is tested

**Comment by brollb** [comment]
yeah, but can you add a test for the interface (to make sure we maintain backwards compatibility)?

**Comment by hamidzr** [comment]
oh the interface tests, right. will do

**Pull request merged**
