### PR TITLE
image retrieval service fixes #1020

### LINKED ISSUE #1020: image retrieval service
we need a reliable way to get images from urls in netsblox.

### PR DESCRIPTION
**Pull request by hamidzr**
image loading service to overcome cors

### CODE REVIEW

**Comment by brollb** [comment]
Are there other things that an `image` service could do? I am not questioning whether we should have this fn-ality; I am just wondering if there would be a better grouping if we add other utility fns like this one.

**Comment by hamidzr** [comment]
Image manipulation or searching for new images.. ? What do you have in mind

**Comment by hamidzr** [comment]
should we merge this with image searching service? @brollb @ellienguyen

**Comment by brollb** [comment]
@hamidzr I think that is a good idea

**Pull request closed without merging**
