### PR TITLE
Adding updated example BritishMuseum

### PR DESCRIPTION
**Pull request by ellienguyen**

### CODE REVIEW

**Comment by hamidzr** [comment]
#1190 is an attempt to speed this up

**Comment by hamidzr** [comment]
please include #1119  in version 0.15.5 to compliment this example

**Comment by brollb** [comment]
Just saw this error - I had thought this was fixed... @hamidzr 

snap0000

**Comment by brollb** [comment]
I am going to merge it since the exception is unrelated to the example itself.

**Comment by brollb** [comment]
Thanks @ellienguyen

**Pull request merged**
